### ISSUE TITLE
Denemekten çekinmeyin.

### ISSUE THREAD

**Issue by numanturle** [erdaltsksn/dene-brew#1]
Yeni bir şeyler denemek iyidir özellikle bu yeni bir dil ise.

**Comment by erdaltsksn** [comment]
başarısız olmaktan değil denememekten korkun

**Comment by numanturle** [comment]
`Eğer herhangi bir şeyi denemek için cesaretimiz olmasa hayatımız ne olur?
Vincent Van Gogh`

**Comment by erdaltsksn** [comment]
@numanturle o zaman beni Go ya alalım. 😅

**Comment by numanturle** [comment]
lütfen buyrunuz efenim.
